title: Blue Earth Community Market
description: Blue Earth's community farmers market. Local food, local people, every Saturday.
url: https://blueearthcommunitymarket.com
baseurl: ""
permalink: /news/:year/:month/:day/:title/

collections:
  posts:
    output: true
